language: python
python:
  # - "2.7"
  - "3.5"
install:
  - pip install mypy-lang==0.4.6
  - pip install -r requirements.txt
cache: pip
script:
  - mypy --silent-imports --check-untyped-defs --scripts-are-modules install.py
